In [1]:
!pip install transformers torch scikit-learn pandas

Requirement already satisfied: transformers in c:\users\kiit0001\anaconda3\lib\site-packages (5.7.0)
Requirement already satisfied: torch in c:\users\kiit0001\anaconda3\lib\site-packages (2.4.1)
Requirement already satisfied: scikit-learn in c:\users\kiit0001\anaconda3\lib\site-packages (1.2.2)
Requirement already satisfied: pandas in c:\users\kiit0001\anaconda3\lib\site-packages (3.0.2)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\kiit0001\anaconda3\lib\site-packages (from transformers) (1.13.0)
Requirement already satisfied: numpy>=1.17 in c:\users\kiit0001\anaconda3\lib\site-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\kiit0001\anaconda3\lib\site-packages (from transformers) (23.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\kiit0001\anaconda3\lib\site-packages (from transformers) (6.0.1)
Requirement already satisfied: regex>=2025.10.22 in c:\users\kiit0001\anaconda3\lib\site-packages (from transformers) (2026.4.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\kiit0001\anaconda3\lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in c:\users\kiit0001\anaconda3\lib\site-packages (from transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\kiit0001\anaconda3\lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in c:\users\kiit0001\anaconda3\lib\site-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock in c:\users\kiit0001\anaconda3\lib\site-packages (from torch) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\users\kiit0001\anaconda3\lib\site-packages (from torch) (4.9.0)
Requirement already satisfied: sympy in c:\users\kiit0001\anaconda3\lib\site-packages (from torch) (1.12)
Requirement already satisfied: networkx in c:\users\kiit0001\anaconda3\lib\site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in c:\users\kiit0001\anaconda3\lib\site-packages (from torch) (3.1.3)
Requirement already satisfied: fsspec in c:\users\kiit0001\anaconda3\lib\site-packages (from torch) (2023.10.0)
Requirement already satisfied: scipy>=1.3.2 in c:\users\kiit0001\anaconda3\lib\site-packages (from scikit-learn) (1.11.4)
Requirement already satisfied: joblib>=1.1.1 in c:\users\kiit0001\anaconda3\lib\site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\kiit0001\anaconda3\lib\site-packages (from scikit-learn) (2.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kiit0001\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata in c:\users\kiit0001\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\kiit0001\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\kiit0001\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: six>=1.5 in c:\users\kiit0001\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: colorama in c:\users\kiit0001\anaconda3\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\kiit0001\anaconda3\lib\site-packages (from jinja2->torch) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in c:\users\kiit0001\anaconda3\lib\site-packages (from sympy->torch) (1.3.0)
Requirement already satisfied: click>=8.2.1 in c:\users\kiit0001\anaconda3\lib\site-packages (from typer->transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\kiit0001\anaconda3\lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\users\kiit0001\anaconda3\lib\site-packages (from typer->transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\kiit0001\anaconda3\lib\site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in c:\users\kiit0001\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.2.0)
Requirement already satisfied: certifi in c:\users\kiit0001\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2024.2.2)
Requirement already satisfied: httpcore==1.* in c:\users\kiit0001\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\kiit0001\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.4)
Requirement already satisfied: h11>=0.16 in c:\users\kiit0001\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\kiit0001\anaconda3\lib\site-packages (from rich>=13.8.0->typer->transformers) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\kiit0001\anaconda3\lib\site-packages (from rich>=13.8.0->typer->transformers) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\kiit0001\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\kiit0001\anaconda3\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.0)

In [2]:
import pandas as pd
import torch
import pickle

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers import Trainer, TrainingArguments

C:\Users\KIIT0001\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.7' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\KIIT0001\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.7' currently installed).
  from pandas.core import (

In [3]:
df = pd.read_csv("emotion_dataset.csv")

df = df.sample(8000, random_state=42)

df.head()

,text,emotion_vector,stress
2388,Help with what?,"[0, 0, 0, 0, 1]",0
4304,It more means nuxia needs help.,"[0, 0, 0, 0, 1]",0
8994,"Sony, for similar design on generic game contr...","[0, 0, 0, 0, 1]",0
14613,This is being said about every fucking update ...,"[0, 0, 1, 0, 0]",2
8087,There's a guy that died after he let a horse d...,"[0, 1, 0, 0, 0]",1

In [4]:
emotions = ["joy", "sadness", "anger", "fear", "neutral"]

def get_emotion_label(vector):
    if isinstance(vector, str):
        vector = eval(vector)
    for i, val in enumerate(vector):
        if val == 1:
            return emotions[i]
    return "neutral"

df["emotion"] = df["emotion_vector"].apply(get_emotion_label)

In [5]:
def combine_label(row):
    return f"{row['emotion']}_{row['stress']}"

df["final_label"] = df.apply(combine_label, axis=1)

In [6]:
le = LabelEncoder()
df["label"] = le.fit_transform(df["final_label"])

print("Total classes:", len(le.classes_))

Total classes: 8

In [7]:
train_texts, val_texts, train_labels, val_labels = train_test_split(
    df["text"].tolist(),
    df["label"].tolist(),
    test_size=0.2,
    random_state=42
)

In [8]:
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

train_encodings = tokenizer(train_texts, truncation=True, padding=True)
val_encodings = tokenizer(val_texts, truncation=True, padding=True)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [9]:
class Dataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

In [10]:
train_dataset = Dataset(train_encodings, train_labels)
val_dataset = Dataset(val_encodings, val_labels)

In [11]:
num_labels = len(df["label"].unique())

model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=num_labels
)

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
pre_classifier.bias     | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [12]:
training_args = TrainingArguments(
    output_dir="./emotion_results",
    learning_rate=2e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=1,
    max_steps=500,   
    weight_decay=0.01,
    logging_steps=10
)

In [13]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset
)

trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=500, training_loss=0.8732720446586609, metrics={'train_runtime': 928.9644, 'train_samples_per_second': 2.153, 'train_steps_per_second': 0.538, 'total_flos': 59513206560000.0, 'train_loss': 0.8732720446586609, 'epoch': 0.3125})

In [14]:
print("Training finished")

Training finished

In [15]:
trainer.evaluate()

{'eval_loss': 0.7438652515411377}

In [16]:
model.save_pretrained("emotion_model")
tokenizer.save_pretrained("emotion_model")

with open("label_encoder.pkl", "wb") as f:
    pickle.dump(le, f)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [18]:
from transformers import pipeline

classifier = pipeline("text-classification", model="emotion_model", tokenizer="emotion_model")

with open("label_encoder.pkl", "rb") as f:
    le = pickle.load(f)

def predict(text):
    result = classifier(text)[0]
    label_index = int(result['label'].split("_")[-1])
    decoded = le.inverse_transform([label_index])[0]

    emotion, stress = decoded.split("_")

    stress_map = {
        "0": "Low",
        "1": "Medium",
        "2": "High"
    }

    return {
        "emotion": emotion.capitalize(),
        "stress": stress_map.get(stress, stress),
        "confidence": round(result['score'], 3)
    }

print(predict("I feel very anxious today"))
print(predict("I am so happy right now"))

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

{'emotion': 'Sadness', 'stress': 'Medium', 'confidence': 0.282}
{'emotion': 'Joy', 'stress': 'Low', 'confidence': 0.452}