In [1]:
!pip install transformers torch scikit-learn pandas

Requirement already satisfied: transformers in c:\users\kiit0001\anaconda3\lib\site-packages (5.7.0)
Requirement already satisfied: torch in c:\users\kiit0001\anaconda3\lib\site-packages (2.4.1)
Requirement already satisfied: scikit-learn in c:\users\kiit0001\anaconda3\lib\site-packages (1.2.2)
Requirement already satisfied: pandas in c:\users\kiit0001\anaconda3\lib\site-packages (3.0.2)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\kiit0001\anaconda3\lib\site-packages (from transformers) (1.13.0)
Requirement already satisfied: numpy>=1.17 in c:\users\kiit0001\anaconda3\lib\site-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\kiit0001\anaconda3\lib\site-packages (from transformers) (23.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\kiit0001\anaconda3\lib\site-packages (from transformers) (6.0.1)
Requirement already satisfied: regex>=2025.10.22 in c:\users\kiit0001\anaconda3\lib\site-packages (from transformers) (2026.4.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\kiit0001\anaconda3\lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in c:\users\kiit0001\anaconda3\lib\site-packages (from transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\kiit0001\anaconda3\lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in c:\users\kiit0001\anaconda3\lib\site-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock in c:\users\kiit0001\anaconda3\lib\site-packages (from torch) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\users\kiit0001\anaconda3\lib\site-packages (from torch) (4.9.0)
Requirement already satisfied: sympy in c:\users\kiit0001\anaconda3\lib\site-packages (from torch) (1.12)
Requirement already satisfied: networkx in c:\users\kiit0001\anaconda3\lib\site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in c:\users\kiit0001\anaconda3\lib\site-packages (from torch) (3.1.3)
Requirement already satisfied: fsspec in c:\users\kiit0001\anaconda3\lib\site-packages (from torch) (2023.10.0)
Requirement already satisfied: scipy>=1.3.2 in c:\users\kiit0001\anaconda3\lib\site-packages (from scikit-learn) (1.11.4)
Requirement already satisfied: joblib>=1.1.1 in c:\users\kiit0001\anaconda3\lib\site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\kiit0001\anaconda3\lib\site-packages (from scikit-learn) (2.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kiit0001\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata in c:\users\kiit0001\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\kiit0001\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\kiit0001\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: six>=1.5 in c:\users\kiit0001\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: colorama in c:\users\kiit0001\anaconda3\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\kiit0001\anaconda3\lib\site-packages (from jinja2->torch) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in c:\users\kiit0001\anaconda3\lib\site-packages (from sympy->torch) (1.3.0)
Requirement already satisfied: click>=8.2.1 in c:\users\kiit0001\anaconda3\lib\site-packages (from typer->transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\kiit0001\anaconda3\lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\users\kiit0001\anaconda3\lib\site-packages (from typer->transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\kiit0001\anaconda3\lib\site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in c:\users\kiit0001\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.2.0)
Requirement already satisfied: certifi in c:\users\kiit0001\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2024.2.2)
Requirement already satisfied: httpcore==1.* in c:\users\kiit0001\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\kiit0001\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.4)
Requirement already satisfied: h11>=0.16 in c:\users\kiit0001\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\kiit0001\anaconda3\lib\site-packages (from rich>=13.8.0->typer->transformers) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\kiit0001\anaconda3\lib\site-packages (from rich>=13.8.0->typer->transformers) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\kiit0001\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\kiit0001\anaconda3\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.0)

In [2]:
!pip install -U accelerate

Collecting accelerate
  Downloading accelerate-1.13.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.17 in c:\users\kiit0001\anaconda3\lib\site-packages (from accelerate) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\kiit0001\anaconda3\lib\site-packages (from accelerate) (23.1)
Requirement already satisfied: psutil in c:\users\kiit0001\anaconda3\lib\site-packages (from accelerate) (5.9.0)
Requirement already satisfied: pyyaml in c:\users\kiit0001\anaconda3\lib\site-packages (from accelerate) (6.0.1)
Requirement already satisfied: torch>=2.0.0 in c:\users\kiit0001\anaconda3\lib\site-packages (from accelerate) (2.4.1)
Requirement already satisfied: huggingface_hub>=0.21.0 in c:\users\kiit0001\anaconda3\lib\site-packages (from accelerate) (1.13.0)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\kiit0001\anaconda3\lib\site-packages (from accelerate) (0.7.0)
Requirement already satisfied: filelock>=3.10.0 in c:\users\kiit0001\anaconda3\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\kiit0001\anaconda3\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (2023.10.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\kiit0001\anaconda3\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\kiit0001\anaconda3\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (0.28.1)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\kiit0001\anaconda3\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (4.67.3)
Requirement already satisfied: typer in c:\users\kiit0001\anaconda3\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (0.25.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\kiit0001\anaconda3\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (4.9.0)
Requirement already satisfied: sympy in c:\users\kiit0001\anaconda3\lib\site-packages (from torch>=2.0.0->accelerate) (1.12)
Requirement already satisfied: networkx in c:\users\kiit0001\anaconda3\lib\site-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in c:\users\kiit0001\anaconda3\lib\site-packages (from torch>=2.0.0->accelerate) (3.1.3)
Requirement already satisfied: anyio in c:\users\kiit0001\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (4.2.0)
Requirement already satisfied: certifi in c:\users\kiit0001\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (2024.2.2)
Requirement already satisfied: httpcore==1.* in c:\users\kiit0001\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (1.0.9)
Requirement already satisfied: idna in c:\users\kiit0001\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (3.4)
Requirement already satisfied: h11>=0.16 in c:\users\kiit0001\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (0.16.0)
Requirement already satisfied: colorama in c:\users\kiit0001\anaconda3\lib\site-packages (from tqdm>=4.42.1->huggingface_hub>=0.21.0->accelerate) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\kiit0001\anaconda3\lib\site-packages (from jinja2->torch>=2.0.0->accelerate) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in c:\users\kiit0001\anaconda3\lib\site-packages (from sympy->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: click>=8.2.1 in c:\users\kiit0001\anaconda3\lib\site-packages (from typer->huggingface_hub>=0.21.0->accelerate) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\kiit0001\anaconda3\lib\site-packages (from typer->huggingface_hub>=0.21.0->accelerate) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\users\kiit0001\anaconda3\lib\site-packages (from typer->huggingface_hub>=0.21.0->accelerate) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\kiit0001\anaconda3\lib\site-packages (from typer->huggingface_hub>=0.21.0->accelerate) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\kiit0001\anaconda3\lib\site-packages (from rich>=13.8.0->typer->huggingface_hub>=0.21.0->accelerate) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\kiit0001\anaconda3\lib\site-packages (from rich>=13.8.0->typer->huggingface_hub>=0.21.0->accelerate) (2.15.1)
Requirement already satisfied: sniffio>=1.1 in c:\users\kiit0001\anaconda3\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (1.3.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\kiit0001\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->huggingface_hub>=0.21.0->accelerate) (0.1.0)
Downloading accelerate-1.13.0-py3-none-any.whl (383 kB)
   ---------------------------------------- 0.0/383.7 kB ? eta -:--:--
   ---------------------------------------- 0.0/383.7 kB ? eta -:--:--
   - -------------------------------------- 10.2/383.7 kB ? eta -:--:--
   - -------------------------------------- 10.2/383.7 kB ? eta -:--:--
   - -------------------------------------- 10.2/383.7 kB ? eta -:--:--
   - -------------------------------------- 10.2/383.7 kB ? eta -:--:--
   - -------------------------------------- 10.2/383.7 kB ? eta -:--:--
   --- ----------------------------------- 30.7/383.7 kB 108.9 kB/s eta 0:00:04
   ---- ---------------------------------- 41.0/383.7 kB 109.3 kB/s eta 0:00:04
   ---- ---------------------------------- 41.0/383.7 kB 109.3 kB/s eta 0:00:04
   ------ -------------------------------- 61.4/383.7 kB 148.8 kB/s eta 0:00:03
   ------- ------------------------------- 71.7/383.7 kB 157.1 kB/s eta 0:00:02
   ----------- -------------------------- 112.6/383.7 kB 226.0 kB/s eta 0:00:02
   -------------- ----------------------- 143.4/383.7 kB 266.2 kB/s eta 0:00:01
   ----------------- -------------------- 174.1/383.7 kB 299.5 kB/s eta 0:00:01
   ---------------------- --------------- 225.3/383.7 kB 353.1 kB/s eta 0:00:01
   --------------------------- ---------- 276.5/383.7 kB 415.4 kB/s eta 0:00:01
   --------------------------------- ---- 337.9/383.7 kB 476.3 kB/s eta 0:00:01
   -------------------------------------  378.9/383.7 kB 512.7 kB/s eta 0:00:01
   -------------------------------------- 383.7/383.7 kB 498.0 kB/s eta 0:00:00
Installing collected packages: accelerate
Successfully installed accelerate-1.13.0

In [3]:
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers import Trainer, TrainingArguments

C:\Users\KIIT0001\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.7' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\KIIT0001\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.7' currently installed).
  from pandas.core import (

In [4]:
df = pd.read_csv("safety_dataset.csv")

df.head()

                                                text  label
0  "aaaand it's intercepted! [NAME] at the goal l...      0
1                         I feel like ending my life      1
2                                     I'm not white.      0
3                               Don't judge our love      0
4                        I want to disappear forever      1

In [5]:
train_texts, val_texts, train_labels, val_labels = train_test_split(
    df["text"].tolist(),
    df["label"].tolist(),
    test_size=0.2,
    random_state=42
)

In [6]:
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

train_encodings = tokenizer(train_texts, truncation=True, padding=True)
val_encodings = tokenizer(val_texts, truncation=True, padding=True)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [7]:
len(train_encodings["input_ids"])

480

In [8]:
class Dataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

In [9]:
train_dataset = Dataset(train_encodings, train_labels)
val_dataset = Dataset(val_encodings, val_labels)

In [10]:
model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=2
)

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [11]:
print(type(model))

<class 'transformers.models.distilbert.modeling_distilbert.DistilBertForSequenceClassification'>

In [12]:
training_args = TrainingArguments(
    output_dir="./results",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=2,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=10
)

[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

In [13]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset
)

trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=120, training_loss=0.16721612885594367, metrics={'train_runtime': 179.0472, 'train_samples_per_second': 5.362, 'train_steps_per_second': 0.67, 'total_flos': 9686678526720.0, 'train_loss': 0.16721612885594367, 'epoch': 2.0})

In [14]:
trainer.evaluate()

{'eval_loss': 0.011958643794059753}

In [15]:
model.save_pretrained("safety_model")
tokenizer.save_pretrained("safety_model")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('safety_model\\tokenizer_config.json', 'safety_model\\tokenizer.json')

In [16]:
from transformers import pipeline

classifier = pipeline("text-classification", model="safety_model", tokenizer="safety_model")

print(classifier("I feel like ending everything"))
print(classifier("I had a great day today"))

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

[{'label': 'LABEL_1', 'score': 0.9908689260482788}]
[{'label': 'LABEL_0', 'score': 0.9744511842727661}]